version: '3.1'

services:
  app:
    container_name: app
    build:
      context: ../
      dockerfile: docker/Dockerfile.python
    expose:
      - 1234

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 90:80
    links:
      - app:app
    depends_on:
      - app
