version: '3.1'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile.python
    expose:
      - 1234

  nginx:
    links:
      - app:app
    build:
      context: ../
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 90:80
    depends_on:
      - app

networks:
  app:
  nginx:
