version: '3.1'
services:
  app:
    build:
      context: ../
    expose:
      - 1234

  nginx:
    image: nginx
    links:
      - app
    build:
      context: ../
      dockerfile: Dockerfile.nginx
    ports:
      - 90:90
    depends_on:
      - app

networks:
  app:
  nginx: