name: Temperature

on:
  push:
    branches:
      - development
      - main
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Get CPU Temperature
        id: temperature
        run: |
          echo "CPU Temp: $(vcgencmd measure_temp | grep  -o -E '[[:digit:]].*')"
